#!/usr/bin/env bash
# Check if an argument is provided
if [ $# -eq 0 ]; then
  echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
  exit 1
else
# Ping the specified IP address 5 times
  ping -c 5 "$1"
fi

